version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.7.1
    - 2.7.3
    - 2.8.0
  - dependency-name: astroid
    versions:
    - 2.5.4
    - 2.5.5
  - dependency-name: importlib-metadata
    versions:
    - 3.6.0
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: s3transfer
    versions:
    - 0.3.5
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
