language: python
dist: xenial
python:
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - make flake8
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
